In [78]:
# Part A: Array Creation & Properties

# Create a 2D NumPy array to store marks of 5 students and 4 subjects.

# Print:

# Number of dimensions

# Shape of the array

# Total number of elements

# Data type of elements
import numpy as np

marks=np.array([
    [78, 85, 90, 88],
    [60, 70, 65, 72],
    [92, 88, 95, 91],
    [45, 55, 50, 48],
    [80, 75, 85, 82]
])


print(marks.ndim)
print(marks.size)
print(marks.shape)
print(marks.dtype)
print("\n")

# Part B: Indexing & Slicing

# Display marks of the first student.

# Display marks of the last student.

# Extract marks of Physics for all students.

# Extract marks of last two students for all subjects.

# Extract a sub-matrix of size (2 × 2) from the center of the array.

print(marks[0])
print(marks[-1])
print(marks[:,1])
print(marks[-2:])
print(marks[1:3,1:3])
print("\n")

# Part C: Statistical Operations

# Find the total marks of each student.

# Find the average marks of each student.

# Find the subject-wise average marks.

# Find the highest and lowest marks in the entire dataset.
print(np.sum(marks,axis=1))
print(np.average(marks,axis=1))
print(np.average(marks,axis=0))
print(np.max(marks))
print(np.min(marks))
print("\n")

# Part D: Boolean Masking

# Identify students who have scored less than 50 in any subject.

# Display marks of students whose average is greater than or equal to 75.

# Count how many students passed all subjects (marks ≥ 40).

print(marks[np.any(marks<50,axis=1)])
print(marks[np.average(marks,axis=1)>=75])
print(np.sum(np.all(marks>=40,axis=1)))
print("\n")

# Part E: Array Operations

# Add 5 grace marks to all students.

# Ensure that no mark exceeds 100 after grace marks.

# Increase only Computer Science marks by 10 using vectorized operation.

print(marks+5)
marks = np.clip(marks, 0, 100)
marks[:,3]=marks[:,3]+10
marks = np.clip(marks, 0, 100)
print(marks)
print("\n")

# Part F: Reshaping & Flattening

# Convert the 2D marks array into a 1D array.

# Reshape the flattened array back to the original shape.

# Use both ravel() and flatten() and observe the difference.

marks.ravel()
marks.reshape(5,4)
marks.flatten()
print(marks)
print("\n")

# Part G: Insert, Delete, Append

# Insert marks of a new subject (English) into the existing array.

# Delete the record of one student.

# Append marks of a new student to the dataset.

marks=np.insert(marks,4,[56,78,89,65,58],axis=1)
marks=np.delete(marks,2,axis=0)
marks=np.append(marks,[[85,70,88,55,75]],axis=0)
print(marks)
print("\n")

# Part H: Copy vs View

# Create a view of the marks array and modify one element.
# Observe whether the original array changes.

# Create a copy of the marks array and modify one element.
# Observe whether the original array changes.

mark=marks.view()
mark[0,2]=34
print(marks)

marks_2=marks.copy()
marks_2[0,2]=36
print(marks)

# Part I: Final Analysis

# Find the overall class average.

# Identify the top-scoring student.

# Identify the weakest subject based on average marks.

# Sort students based on total marks.

print(np.average(marks))
print(np.argmax(np.sum(marks,axis=1)))
print(np.argmin(np.average(marks,axis=0)))
print(np.argsort(np.sum(marks,axis=1)))


2
20
(5, 4)
int64


[78 85 90 88]
[80 75 85 82]
[85 70 88 55 75]
[[45 55 50 48]
 [80 75 85 82]]
[[70 65]
 [88 95]]


[341 267 366 198 322]
[85.25 66.75 91.5  49.5  80.5 ]
[71.  74.6 77.  76.2]
95
45


[[45 55 50 48]]
[[78 85 90 88]
 [92 88 95 91]
 [80 75 85 82]]
5


[[ 83  90  95  93]
 [ 65  75  70  77]
 [ 97  93 100  96]
 [ 50  60  55  53]
 [ 85  80  90  87]]
[[ 78  85  90  98]
 [ 60  70  65  82]
 [ 92  88  95 100]
 [ 45  55  50  58]
 [ 80  75  85  92]]


[[ 78  85  90  98]
 [ 60  70  65  82]
 [ 92  88  95 100]
 [ 45  55  50  58]
 [ 80  75  85  92]]


[[78 85 90 98 56]
 [60 70 65 82 78]
 [45 55 50 58 65]
 [80 75 85 92 58]
 [85 70 88 55 75]]


[[78 85 34 98 56]
 [60 70 65 82 78]
 [45 55 50 58 65]
 [80 75 85 92 58]
 [85 70 88 55 75]]
[[78 85 34 98 56]
 [60 70 65 82 78]
 [45 55 50 58 65]
 [80 75 85 92 58]
 [85 70 88 55 75]]
69.68
3
2
[2 0 1 4 3]
